[package]
name        = "rustybones"
version     = "0.1.0"
authors     = ["Matti Hänninen <matti@mjhanninen.com>"]
license     = "GPL-3.0-or-later"
edition     = "2021"

[dependencies]
hmac-sha256 = "1.1.7"
